to: pdf
metadata:
  author:
    - 张诚
pdf-engine: xelatex

table-of-contents: true
toc-depth: 2

variables:
  toc-title: 目录
  CJKmainfont: WenQuanYi Micro Hei
  geometry: "top=2cm, bottom=1.5cm, left=2cm, right=2cm"

highlight-style: tango
